version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb_superflights
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
      - MONGO_INITDB_DATABASE=superflights
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
    networks:
      - superflights-network

networks:
  superflights-network:
    driver: bridge

volumes:
  mongodb_data:
    driver: local
